# 定义stages
stages:
  - build
  - deploy
  - sonarqube-check

# variables:
#   # 镜像仓
#   IMAGE_REGISTRY: ccr.ccs.tencentyun.com/gct_dev
#   # license运营管理平台后台
#   LICENSE_IMAGE_VERSION: ${IMAGE_REGISTRY}/gct-license:${CI_COMMIT_BRANCH}
#   # kubeconfig 配置文件名
#   KUBECONFIGFILE: dev
#   # runner中kubeconfig路径
#   KUBECONFIG: /root/.kube/config
#   # 服务所在k8s集群namespace
#   NAMESPACE: dev



build_dockerfile:
  # 编译镜像
  #image: ccr.ccs.tencentyun.com/gct_dev/ubuntu22-04:jdk11-22.3.2
  # when: manual
  stage: build
#   only:
#     # 触发条件
#     refs:
#       # 分支
#       - /^dev-.*/
#       - /^test-.*/
#       - /^vm-.*/
  # tags:
  #   - gct_apaas_bed
  # 重试次数
  retry:
    max: 2
  script:
    - docker build -t node:18.3.20 ./dockerfile/
    - docker push node:18.3.20
