---
name: CI
on:
  pull_request:
  push:
  

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-latest
    container:
      # Whenever the Go version is updated here, .promu.yml
      # should also be updated.
      image: docker
    steps:
      # - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      # - uses: prometheus/promci@3cb0c3871f223bd5ce1226995bd52ffb314798b6 # v0.1.0
      # - uses: ./.github/promci/actions/setup_environment
      - run: docker build -t node:1212 ../../dockerfile/
