name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/mytest_docker123/redis:6.2.12
    
   
    - name: docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_LOGIN_URL }}
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}   
        
    #   run: docker login --username=xadrsysh --password=December@1 registry.cn-hangzhou.aliyuncs.com

    - name: docker push 
      run: docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/redis:6.2.12
