name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/yushihao/node:18.3.20
    - name: docker login
      run: docker login --username=${DOCKER_LOGIN_USER} -p ${DOCKER_LOGIN_PASS} ${DOCKER_LOGIN_URL}
    - name: docker push 
      run: docker push registry.cn-hangzhou.aliyuncs.com/yushihao/node:18.3.20
